# Generated by Django 3.2.4 on 2021-06-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animecharacter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alias_name', models.CharField(max_length=200)),
                ('anime_name', models.CharField(max_length=200)),
                ('anime_seasons', models.IntegerField()),
                ('role_in_anime', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
